#!/usr/bin/env bash
# This script starts, stops, or restarts the manage_my_process script

ACTION=$1

case "$ACTION" in
    start)
        ./manage_my_process &
        echo "$!" > /var/run/my_process.pid
        ;;
    stop)
        if [ -f /var/run/my_process.pid ]; then
            kill "$(cat /var/run/my_process.pid)"
            rm /var/run/my_process.pid
            echo "process stopped"
        else
            echo "process is not running"
        fi
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
